### ISSUE TITLE
xpdf-poppler faills compilation against poppler master

### ISSUE THREAD

**Issue by jhcloos** [rbrito/xpdf-poppler#16]
SplashOutputDev::setFreeTypeHinting(bool) has (it seems) been replaced with SplashOutputDev::setFreeTypeHinting(bool, bool), leading to:

/work/xpdf-master/CoreOutputDev.cc: In constructor 'CoreOutputDev::CoreOutputDev(SplashColorMode, int, bool, SplashColorPtr, bool, CoreOutRedrawCbk, void_)':
/work/xpdf-master/CoreOutputDev.cc:33:65: error: no matching function for call to 'CoreOutputDev::setFreeTypeHinting(GBool)'
/work/xpdf-master/CoreOutputDev.cc:33:65: note: candidate is:
/usr/include/poppler/SplashOutputDev.h:380:8: note: void SplashOutputDev::setFreeTypeHinting(GBool, GBool)
/usr/include/poppler/SplashOutputDev.h:380:8: note:   candidate expects 2 arguments, 1 provided
make: *_\* [xpdf_poppler-CoreOutputDev.o] Error 1

**Comment by TimothyGu** [comment]
This was fixed in 7e4aeaf49b409f1ea67311566d6c80016f5aa97b.
