### ISSUE TITLE
The linked blog post is down

### ISSUE THREAD

**Issue by SamB** [rbrito/xpdf-poppler#21]
You link to what appears to be a post on your blog, http://rb.doesntexist.org/blog/posts/please-let-me-zoom-my-documents-/.  Unfortunately, this post appears to be down.  (In fact, it looks kind of like the whole domain is down.)

**Comment by rbrito** [comment]
Oh, sure. I have changed domains.

Thank you very much for letting me know. If you find other references that should be changed, please let me know too.
