### ISSUE TITLE
no "zoom to selection"

### ISSUE THREAD

**Issue by khaledhosny** [rbrito/xpdf-poppler#4]
Regular xpdf has a zoom to selection menu item which is very handy when one wants to inspect a certain part of the document. It is missing from xpdf-poppler.

**Comment by rbrito** [comment]
Thanks for reporting this. I will take a look at what is missing and how to address it.

**Comment by rbrito** [comment]
Hi, Khaled.

Just for your information, the version on which I based xpdf-poppler was xpdf 3.01 and it didn't have this implemented. I am forward porting the changes to xpdf-poppler.

Thanks for the report.

**Comment by rbrito** [comment]
Hi, Khaled.

This is already fixed in the branch xpdf 3.02.
